apiVersion: v1
kind: Service
metadata:
  name: tasksdatabaseservice
  labels:
    name: tasksdatabasestatefulset
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
